### ISSUE TITLE
Feature Request: API for Converting SVG to PNG

### ISSUE THREAD

**Issue by dreamjet31** [vincerubinetti/svg-to-png#16]
Hello,

Firstly, I want to express my appreciation for this project. The speed and superb results have greatly benefitted my work. However, I've hit a snag and would appreciate your help.

I am currently working on a Python project where I need to incorporate the functionality that your project offers - specifically, converting SVG files to PNG. As you may know, Python isn't compatible with TypeScript, which leaves me in a difficult spot.

To navigate around this issue, I was hoping you might consider developing an API that takes an SVG file path URL and returns a PNG file path URL. This way, I can continue to benefit from your great work without the language barrier.

Given an SVG file path URL such as https://sample.com/inputfile.svg, the API would return the PNG file path URL, e.g., https://vincerubinetti.github.io/svg-to-png/output.png.

Looking forward to your constructive response.

Thank you.

**Comment by vincerubinetti** [comment]
Thinking about this more, I don't think I'm prepared to commit to this feature at this time.

Ultimately, the browser is doing the real work of the conversion, thus a browser must be running to serve the request. So, I would have to have a server that is constantly running instances of Playwright/Puppeteer/Electron/whatever to process requests, or a cloud function that just starts up a new instance on each request. Either way, this is a monetary and time cost that I can't commit to right now.

If anyone knows of an easy/free way to accomplish this, let me know.

**Comment by vincerubinetti** [comment]
However, in your very specific case, you could possibly do something like the following.

In your Python code, use `playwright-python` to programmatically open this webapp locally in your browser, [upload the files you need to convert](https://playwright.dev/python/docs/api/class-filechooser), then [download the output](https://playwright.dev/python/docs/downloads).
